# Generated by Django 6.0.5 on 2026-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_rename_department_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='token',
            field=models.IntegerField(default=1),
        ),
    ]
